version: '2'

services:
  temper_database:
      container_name: temper_database_container
      restart: always
      build:
        context: ./docker/database
      environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: temper
  nginx:
    container_name: temper_nginx_container
    build:
        context: .
        dockerfile: docker/nginx/Dockerfile
    volumes:
          - .:/var/www/html
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./docker/nginx/sites/:/etc/nginx/sites-available
          - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "7070:80"
      - "443:443"
  php-fpm:
      container_name: temper_php_fpm_container
      links:
         - temper_database
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      volumes:
            - .:/var/www/html
  phpmyadmin:
       container_name: temper_phpmyadmin_container
       image: phpmyadmin/phpmyadmin
       ports:
         - "9090:80"
       links:
         - temper_database:mysql_db_server
       environment:
         MYSQL_ROOT_PASSWORD: '123456'
         MYSQL_USER: 'root'
         MYSQL_PASSWORD: '123456'
         PMA_HOST: mysql_db_server
         PMA_USER: root
         PMA_PASSWORD: '123456'
         PMA_PORT: 3306